2025-06-23 14:10:57,716 - ERROR - Unhandled exception: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
2025-06-23 14:11:22,711 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:11:38,918 - ERROR - Error processing None: 'Medicaid'
2025-06-23 14:11:47,870 - ERROR - Error processing None: 'Medicaid'
2025-06-23 14:11:57,405 - ERROR - Error processing None: 'Medicaid'
2025-06-23 14:12:07,263 - ERROR - Error processing None: 'Medicaid'
2025-06-23 14:12:16,065 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002254A1CC4D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eef9e778909db7764624ecffd8a7694e/element
2025-06-23 14:12:20,115 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000225497054D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eef9e778909db7764624ecffd8a7694e/element
2025-06-23 14:12:24,132 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002254A1BE590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eef9e778909db7764624ecffd8a7694e/element
2025-06-23 14:12:28,162 - ERROR - Error processing None: HTTPConnectionPool(host='localhost', port=55375): Max retries exceeded with url: /session/eef9e778909db7764624ecffd8a7694e/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022549DC9ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:12:32,181 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022537929190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eef9e778909db7764624ecffd8a7694e/execute/sync
2025-06-23 14:13:11,840 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:13:49,615 - ERROR - Error processing GG80169F: 'list' object has no attribute 'strip'
2025-06-23 14:14:21,066 - ERROR - Error processing YA55004Z: 'list' object has no attribute 'strip'
2025-06-23 14:14:52,892 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914B0D5C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/element
2025-06-23 14:14:56,917 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914B8A7C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/element
2025-06-23 14:15:00,945 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029138F29ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/element
2025-06-23 14:15:04,974 - ERROR - Error processing XT98243B: HTTPConnectionPool(host='localhost', port=55558): Max retries exceeded with url: /session/632493316793a1cb7c7f668437e6e795/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000291393C9D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:15:08,984 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BD99650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:15:13,012 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BD99D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:15:17,031 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BD9A750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:15:21,058 - ERROR - Error processing YP03884U: HTTPConnectionPool(host='localhost', port=55558): Max retries exceeded with url: /session/632493316793a1cb7c7f668437e6e795/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BD9B110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:15:25,074 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BD9BC10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:15:29,092 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BDA07D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:15:33,108 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914B8D54D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:15:37,133 - ERROR - Error processing YS87180G: HTTPConnectionPool(host='localhost', port=55558): Max retries exceeded with url: /session/632493316793a1cb7c7f668437e6e795/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914B8B65D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:15:41,140 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029138F26150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:15:45,155 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914B3C2E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:15:49,171 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BD9B490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:15:53,192 - ERROR - Error processing YG92852H: HTTPConnectionPool(host='localhost', port=55558): Max retries exceeded with url: /session/632493316793a1cb7c7f668437e6e795/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BD9AA50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:15:57,213 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BD992D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:16:01,231 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BD99950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:16:05,263 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BDA1150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/632493316793a1cb7c7f668437e6e795/execute/sync
2025-06-23 14:16:09,280 - ERROR - Error processing WZ53496D: HTTPConnectionPool(host='localhost', port=55558): Max retries exceeded with url: /session/632493316793a1cb7c7f668437e6e795/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002914BDA1B10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:21:51,067 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:22:34,559 - INFO - Processed GG80169F successfully.
2025-06-23 14:23:09,671 - INFO - Processed YA55004Z successfully.
2025-06-23 14:23:46,283 - INFO - Processed XT98243B successfully.
2025-06-23 14:24:22,314 - INFO - Processed YP03884U successfully.
2025-06-23 14:24:57,610 - INFO - Processed YS87180G successfully.
2025-06-23 14:25:33,881 - INFO - Processed YG92852H successfully.
2025-06-23 14:26:12,053 - INFO - Processed WZ53496D successfully.
2025-06-23 14:26:43,336 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:27:20,119 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827ABDC90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/element
2025-06-23 14:27:24,203 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E813831290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/element
2025-06-23 14:27:28,278 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E814ACE450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/element
2025-06-23 14:27:32,363 - ERROR - Error processing GG80169F: HTTPConnectionPool(host='localhost', port=56537): Max retries exceeded with url: /session/e9685af375dbe1207d29aa8be8b438cf/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827850190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:27:36,448 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827852810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:27:40,533 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827853D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:27:44,624 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827851C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:27:48,705 - ERROR - Error processing YA55004Z: HTTPConnectionPool(host='localhost', port=56537): Max retries exceeded with url: /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827357010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:27:52,775 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279D89D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:27:56,838 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279DB8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:00,942 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279DAED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:05,026 - ERROR - Error processing XT98243B: HTTPConnectionPool(host='localhost', port=56537): Max retries exceeded with url: /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279DA650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:28:09,090 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279D9910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:13,187 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279CB890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:17,271 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279CB790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:21,372 - ERROR - Error processing YP03884U: HTTPConnectionPool(host='localhost', port=56537): Max retries exceeded with url: /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279CAAD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:28:25,450 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279DA150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:29,536 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279DB750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:33,630 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279DBA10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:37,702 - ERROR - Error processing YS87180G: HTTPConnectionPool(host='localhost', port=56537): Max retries exceeded with url: /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8279D80D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:28:41,803 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E814ACE490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:45,896 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E814D26150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:49,968 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827851050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:28:54,071 - ERROR - Error processing YG92852H: HTTPConnectionPool(host='localhost', port=56537): Max retries exceeded with url: /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827853390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:28:58,162 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827852050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:29:02,247 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827852950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:29:06,334 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827850910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync
2025-06-23 14:29:10,409 - ERROR - Error processing WZ53496D: HTTPConnectionPool(host='localhost', port=56537): Max retries exceeded with url: /session/e9685af375dbe1207d29aa8be8b438cf/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E827B95590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:29:24,422 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:30:06,146 - INFO - Processed GG80169F successfully.
2025-06-23 14:30:13,047 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:30:36,884 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000295F5663290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6bbe9d556e9e4fb2ed86aa63854f1816/element
2025-06-23 14:30:40,933 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000295E289FD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6bbe9d556e9e4fb2ed86aa63854f1816/element
2025-06-23 14:30:45,014 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000295F5007510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6bbe9d556e9e4fb2ed86aa63854f1816/element
2025-06-23 14:30:49,088 - ERROR - Error processing GG80169F: HTTPConnectionPool(host='localhost', port=56864): Max retries exceeded with url: /session/6bbe9d556e9e4fb2ed86aa63854f1816/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000295F4A8DDD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-23 14:32:26,262 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:33:07,577 - INFO - Processed GG80169F successfully.
2025-06-23 14:33:10,099 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:33:52,140 - INFO - Processed GG80169F successfully.
2025-06-23 14:37:53,361 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:38:35,111 - INFO - Processed GG80169F successfully.
2025-06-23 14:39:06,790 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:39:47,790 - INFO - Processed GG80169F successfully.
2025-06-23 14:41:16,594 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:41:57,536 - INFO - Processed GG80169F successfully.
2025-06-23 14:41:59,699 - INFO - patching driver executable C:\Users\liu17\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-06-23 14:42:17,656 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013A34A9FC50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ec59ff8912adcd769b0b7e9bd3d8a2cb/element
2025-06-23 14:42:21,769 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013A21CDE950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ec59ff8912adcd769b0b7e9bd3d8a2cb/element
2025-06-23 14:42:25,841 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013A21CD0DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ec59ff8912adcd769b0b7e9bd3d8a2cb/element
2025-06-23 14:42:29,921 - ERROR - Error processing GG80169F: HTTPConnectionPool(host='localhost', port=58697): Max retries exceeded with url: /session/ec59ff8912adcd769b0b7e9bd3d8a2cb/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013A21F18750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
